- name: IBM community grid managed nodes
  hosts: "managed_nodes"
  become: true
  gather_facts: true

  tasks:
    - name: install boinc-client and register
      include_role:
        name: ansible.workshops.community_grid
      when:
        - ibm_community_grid is defined
        - ibm_community_grid

- name: IBM community grid control node
  hosts: "control_nodes"
  become: true
  gather_facts: true

  tasks:
    - name: install boinc-client and register
      include_role:
        name: ansible.workshops.community_grid
        tasks_from: auto_shutoff
      when:
        - ibm_community_grid is defined
        - ibm_community_grid
